# Generated by Django 5.1.15 on 2026-06-06 22:14

from django.db import migrations, models

import brief.models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="BriefRequestLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "public_id",
                    models.CharField(
                        db_index=True,
                        default=brief.models._generate_public_id,
                        editable=False,
                        max_length=24,
                        unique=True,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("brand", models.CharField(max_length=80)),
                ("platform", models.CharField(max_length=20)),
                ("goal", models.CharField(max_length=20)),
                ("tone", models.CharField(max_length=20)),
                ("provider", models.CharField(max_length=20)),
                ("model", models.CharField(max_length=80)),
                ("latency_ms", models.IntegerField()),
                ("input_tokens", models.IntegerField()),
                ("output_tokens", models.IntegerField()),
                ("cost_usd", models.DecimalField(decimal_places=6, max_digits=10)),
                ("result", models.JSONField(default=dict)),
                ("client_ip", models.GenericIPAddressField(blank=True, null=True)),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
    ]
