# Generated by Django 5.1.15 on 2026-06-06 22:56

from django.db import migrations, models

import brief.models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="BriefRequestLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "public_id",
                    models.CharField(
                        default=brief.models._generate_public_id,
                        editable=False,
                        max_length=24,
                        unique=True,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("brand", models.CharField(max_length=80)),
                (
                    "platform",
                    models.CharField(
                        choices=[("Instagram", "Instagram"), ("TikTok", "TikTok"), ("UGC", "UGC")],
                        max_length=20,
                    ),
                ),
                (
                    "goal",
                    models.CharField(
                        choices=[
                            ("Awareness", "Awareness"),
                            ("Conversions", "Conversions"),
                            ("Content Assets", "Content Assets"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "tone",
                    models.CharField(
                        choices=[
                            ("Professional", "Professional"),
                            ("Friendly", "Friendly"),
                            ("Playful", "Playful"),
                        ],
                        max_length=20,
                    ),
                ),
                ("provider", models.CharField(max_length=20)),
                ("model", models.CharField(max_length=80)),
                ("latency_ms", models.PositiveIntegerField()),
                ("input_tokens", models.PositiveIntegerField()),
                ("output_tokens", models.PositiveIntegerField()),
                ("cost_usd", models.DecimalField(decimal_places=6, max_digits=10)),
                ("result", models.JSONField(default=dict)),
                ("client_ip", models.GenericIPAddressField(blank=True, null=True)),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(fields=["-created_at"], name="brief_created_idx"),
                    models.Index(fields=["model"], name="brief_model_idx"),
                    models.Index(fields=["client_ip"], name="brief_client_ip_idx"),
                ],
            },
        ),
    ]
